# -*- coding: utf-8 -*-
"""Anscombes_quartet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNux_G_tPxrzIolJqZkgGABgbSAOUXM7
"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

# This line of code reads the dataset named 'df_anscombe.csv', which is stored in the same directory as this notebook.
df_anscombe = pd.read_csv('/df_anscombe.csv')

"""# New Section"""

df_anscombe.head()

df_anscombe.group.nunique()

df_anscombe.groupby('group').describe()

df_anscombe.groupby('group').corr()

groups = df_anscombe.groupby('group')


# Setting up the subplots - 2 rows, 2 columns
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Flattening the axes array to easily iterate over it
axes = axes.flatten()

# Plotting each group in a different subplot
for (name, group), ax in zip(groups, axes):
    ax.scatter(group['x'], group['y'])
    ax.set_title(f'Group {name}')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.grid(True)

# Adjust layout to prevent overlap
plt.tight_layout()

# Display the plots
plt.show()